mysql:
  host: 145.239.88.2:3306
  database: s1802_testdb
  username: u1845_caz1T2v2ft
  password: '0=b+8zsztXD=qQHjSuQ+ZHRz'
gui:
  list:
    title:
      local: 'Локальные метки №%page%'
      global: 'Глобальные метки №%page%'
      remove: '&cУдаление метки'
    nopage:
      material: BARRIER
      amount: 1
      name: '&cБольше нету страниц!'
      lore:
      - ''
    nextPage:
      material: ARROW
      amount: 1
      name: '&6Следующая страница'
      lore:
      - ''
    previousPage:
      material: ARROW
      amount: 1
      name: '&6Предыдущая страница'
      lore: 
      - ''
    selected:
      material: STRUCTURE_VOID
      amount: 1
      name: '&3Метка успешно выбрана!'
      lore: 
      - ''
  confirmation:
    title: 'Вы уверены?'
    yeah:
        material: ARROW
        amount: 1
        name: '&aДа'
        lore:
        - ''
    nope: 
        material: RED_WOOL
        amount: 1
        name: '&cНет'
        lore:
        - ''
worldguard:
  enabled: false
waypoints:
  holograms:
    enabled: true
    distance:
      enabled: true
    podzkazka:
      enabled: true
      text: '&cИди сюда!'
  actionbar: 
    enabled: false
maptag:
  name: 'Метка %maptag%'
  worlds:
  - 'world:&aМир'
  - 'world_nether:&cНезер'
  - 'world_the_end:&eЭнд'
  customcolorname:
  - 'Дом:&a'
  lore:
  - '%lore%'
  - 'Владелец: %owner%'
  - 'Мир: %world%'
  - 'Координаты: %location%'
  - '&fid: %id%'
  defaultItem: DIRT
 



  
