mysql:
  host: 145.239.88.2:3306
  database: s1802_testdb
  username: u1802_bQM41kpdVL
  password: 'TV..agKoIwfq.rBsbrqMJ8zA'
gui:
  list:
    title:
      local: 'Локальные метки №%page%'
      global: 'Глобальные метки №%page%'
    nopage:
      material: BARRIER
      amount: 1
      name: '&cБольше нету страниц!'
      lore:
      - ''
    nextPage:
      material: ARROW
      amount: 1
      name: '&6Следующая страница'
      lore:
      - ''
    previousPage:
      material: ARROW
      amount: 1
      name: '&6Предыдущая страница'
      lore: 
      - ''
    selected:
      material: STRUCTURE_VOID
      amount: 1
      name: '&3Метка успешно выбрана!'
      lore: 
      - ''
worldguard:
  enabled: false
