name: MapTags
main: me.gepron1x.maptags.MapTagsPlugin
description: 228
version: 1.3.37
authors: [NukerFall, gepron1x]
api-version: 1.13
softdepend: [WorldGuard, WorldEdit]
commands:
   maptag:
      description: cringe